/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */


/**
 * Event raised by a {@link module:filters.ZBarFilter ZBarFilter} when a code is
 *
 * @event module:filters#CodeFound
 *
 * @type {module:filters#event:Media}
 *
 * @property {external:String} codeType
 *  type of <a 
 *  href="http://www.kurento.org/docs/current/glossary.html#term-qr">QR</a> code
 * @property {external:String} value
 *  value contained in the <a 
 *  href="http://www.kurento.org/docs/current/glossary.html#term-qr">QR</a> code
 */
