/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Event raised by a {@link module:filters.ZBarFilter ZBarFilter} when a code is
 *
 * @event module:filters#CodeFound
 *
 * @type {module:filters#event:Media}
 *
 * @property {external:String} codeType
 *  type of <a 
 *  href="http://www.kurento.org/docs/current/glossary.html#term-qr">QR</a> code
 * @property {external:String} value
 *  value contained in the <a 
 *  href="http://www.kurento.org/docs/current/glossary.html#term-qr">QR</a> code
 */
