/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var Filter = require('kurento-client-filters').abstracts.Filter;

/**
 * Builder for the {@link module:filters.ZBarFilter ZBarFilter}.
 *
 * @classdesc
 *  This filter detects <a href="http://www.kurento.org/docs/current/glossary.html#term-qr">QR</a> codes in a video feed. When a code is found, the filter raises a :rom:evnt:`CodeFound` event.
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:filters.ZBarFilter
 *
 * @param {external:String} id
 *
 * @fires {@link module:filters#event:CodeFound CodeFound}
 */
function ZBarFilter(id){
  Filter.call(this, id);
};
inherits(ZBarFilter, Filter);

/**
 * @alias module:filters.ZBarFilter.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the {@link module:core.MediaPipeline MediaPipeline} to which the filter belongs
 */
ZBarFilter.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  },
};

/**
 * @alias module:filters.ZBarFilter.events
 *
 * @extend module:core/abstracts.Filter.events
 */
ZBarFilter.events = ['CodeFound'];
ZBarFilter.events.concat(Filter.events);

module.exports = ZBarFilter;

ZBarFilter.check = function(key, value)
{
  if(!(value instanceof ZBarFilter))
    throw SyntaxError(key+' param should be a ZBarFilter, not '+typeof value);
};
